### ISSUE TITLE
[Vssue]你不知道的javascript(中)语法 | HEROES NEVER DIE

### ISSUE THREAD

**Issue by hdulsh** [hdulsh/vuepress-blog#1]
https://limeili.co/views/javascript/%E4%BD%A0%E4%B8%8D%E7%9F%A5%E9%81%93%E7%9A%84javascript%20%E4%B8%AD%20%E8%AF%AD%E6%B3%95.html

**Comment by hdulsh** [comment]
评论

**Comment by 29601259** [comment]
嗷嗷嗷
