### ISSUE TITLE
[Vssue]你不知道的javascript(上)作用域和闭包 | HEROES NEVER DIE

### ISSUE THREAD

**Issue by hdulsh** [hdulsh/vuepress-blog#2]
https://limeili.co/views/javascript/%E4%BD%A0%E4%B8%8D%E7%9F%A5%E9%81%93%E7%9A%84javascript%20%E4%B8%8A%20%E4%BD%9C%E7%94%A8%E5%9F%9F%E5%92%8C%E9%97%AD%E5%8C%85.html

**Comment by hdulsh** [comment]
评论

**Comment by 29601259** [comment]
哦哦哦
