### ISSUE TITLE
[Vssue]理解 Javascript 执行上下文和执行栈 | HEROES NEVER DIE

### ISSUE THREAD

**Issue by hdulsh** [hdulsh/vuepress-blog#3]
https://limeili.co/views/javascript/%E7%90%86%E8%A7%A3Javascript%E6%89%A7%E8%A1%8C%E4%B8%8A%E4%B8%8B%E6%96%87%E5%92%8C%E6%89%A7%E8%A1%8C%E6%A0%88.html

**Comment by 29601259** [comment]
哦哦哦
